export const GET_SESSIONS = 'GET_SESSIONS';
export const ADD_SESSION = 'ADD_SESSION';
export const ADD_COURSE = 'ADD_COURSE';
export const DOWNLOAD_SESSION = 'DOWNLOAD_SESSION';
export const SESSIONS_LOADING = 'SESSIONS_LOADING';

export const GET_RECORDS = 'GET_RECORDS';
export const ADD_RECORD = 'ADD_RECORD';
export const DOWNLOAD_RECORD = 'DOWNLOAD_RECORD';
export const RECORDS_LOADING = 'RECORDS_LOADING';
export const ADD_STUDENT_COMMENT = 'ADD_STUDENT_COMMENT';

export const GET_PROFESSOR = 'GET_PROFESSOR';
export const ADD_PROFESSOR = 'ADD_PROFESSOR';
export const DOWNLOAD_PROFESSOR = 'DOWNLOAD_PROFESSOR';
export const PROFESSOR_LOADING = 'PROFESSOR_LOADING';

export const GET_STUDENT = 'GET_STUDENT';
export const ADD_STUDENT = 'ADD_STUDENT';
export const DOWNLOAD_STUDENT = 'DOWNLOAD_STUDENT';
export const STUDENT_LOADING = 'STUDENT_LOADING';
